name: Documentation

on:
  workflow_dispatch: {}
  push:
    branches:
      - doc-deploy
    paths:
      - .github/workflows/documentation.yaml
      - Sources/**.swift

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          inputs: "Sources"
          output: "Documentation"
      - name: Upload Documentation Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=Documentation --functions=functions
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}